import { JWT } from 'google-auth-library';
import { GoogleSpreadsheet } from 'google-spreadsheet';
import { useEffect, useState } from 'react';
import { getQueuedMatches } from '../src/util/idb';

// Define the structure of your dynamic form data
interface MatchPayload {
  [key: string]: any;
}

// Define the expected structure of the incoming match JSON
interface MatchData {
  payload: MatchPayload;
  teamNumber: number | string;
  matchNumber: number | string;
  scouter: string;
  timestamp: string | number;
}

async function syncToSheets() {
  const [matches, setMatches] = useState<MatchData[]>([]);

  // Read the JSON file generated by your app or previous workflow steps
  const refreshQueue = async () => {
    try {
      const matches = await getQueuedMatches();
      setMatches(matches);
    } catch {
      setMatches([]);
    }
  };

  useEffect(() => {
    refreshQueue();
    // Poll every 5 seconds to catch newly saved matches
    const interval = setInterval(refreshQueue, 5000);
    return () => clearInterval(interval);
  }, []);
  if (!matches || matches.length === 0) {
    console.log('No matches to sync.');
    return;
  }

  // Ensure secrets are available in the GitHub Actions environment
  if (
    !process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL ||
    !process.env.GOOGLE_PRIVATE_KEY ||
    !process.env.GOOGLE_SHEET_ID
  ) {
    console.error('Missing Google Sheets credentials.');
    process.exit(1);
  }

  // Authenticate using the service account
  const serviceAccountAuth = new JWT({
    email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,
    key: process.env.GOOGLE_PRIVATE_KEY.replace(/\\n/g, '\n'),
    scopes: ['https://www.googleapis.com/auth/spreadsheets'],
  });

  const doc = new GoogleSpreadsheet(
    process.env.GOOGLE_SHEET_ID,
    serviceAccountAuth,
  );
  await doc.loadInfo();

  // Find the target sheet
  let sheet = doc.sheetsByTitle['Matches'];
  if (!sheet) {
    sheet = doc.sheetsByIndex[0];
  }

  // Flatten the data for Google Sheets
  const rowsToAdd = matches.map(m => {
    return {
      ...m.payload,
      teamNumber: m.teamNumber,
      matchNumber: m.matchNumber,
      scouter: m.scouter,
      timestamp: new Date(m.timestamp).toISOString(),
    };
  });

  // Extract all unique keys to ensure headers are up to date
  const headersNeeded = new Set<string>();
  rowsToAdd.forEach(row => {
    Object.keys(row).forEach(k => headersNeeded.add(k));
  });

  const existingHeaders = [...sheet.headerValues];
  const missingHeaders = Array.from(headersNeeded).filter(
    h => !existingHeaders.includes(h),
  );

  // Append new headers if your dynamic payload added new fields
  if (missingHeaders.length > 0) {
    await sheet.setHeaderRow([...existingHeaders, ...missingHeaders]);
  }

  // Push the data
  await sheet.addRows(rowsToAdd);
  console.log(`Successfully synced ${rowsToAdd.length} matches.`);
}

// Execute the script
syncToSheets().catch(console.error);
